### PR TITLE
correct_image_size

### PR DESCRIPTION
**Pull request by santiestrada32**
Correct image size

### CODE REVIEW

**Comment by dkuegler** [comment]
deny; use image by @christianewert 
you can also send the image to @christianewert so he can prepare the image to "fit properly"

**Comment by santiestrada32** [comment]
@dkuegler  Which image?  i commit 3

**Comment by dkuegler** [comment]
@santiestrada32 the ones you want to be on the webpage...

**Comment by dkuegler** [comment]
@santiestrada32 sorry, just member images

**Comment by santiestrada32** [comment]
@dkuegler, ok will cancel my member image commit

**Comment by dkuegler** [comment]
Sorry this might have been confusing. publication images are still good :)
Sorry for confusion...

**Pull request closed without merging**
